export const GET_COMISSION_CONFIG_LIST = 'GET_COMISSION_CONFIG_LIST';
export const GET_COMISSION_CONFIG_USER_POSITION = 'GET_COMISSION_CONFIG_USER_POSITION';
export const GET_COMISSION_CONFIG_FORM_DATA_TYPE = 'GET_COMISSION_CONFIG_FORM_DATA_TYPE';
export const GET_COMISSION_CONFIG_FORM_DATA_FORMULAR_OPERATOR = 'GET_COMISSION_CONFIG_FORM_DATA_FORMULAR_OPERATOR';
export const GET_COMISSION_CONFIG_FORM_DATA_FORMULAR_LOGICAL = 'GET_COMISSION_CONFIG_FORM_DATA_FORMULAR_LOGICAL';
export const GET_COMISSION_CONFIG_FORM_DATA_FORMULAR_TYPE = 'GET_COMISSION_CONFIG_FORM_DATA_FORMULAR_TYPE';
export const GET_COMISSION_CONFIG_FORM_DATA_FORMULAR_CURRENCY = 'GET_COMISSION_CONFIG_FORM_DATA_FORMULAR_CURRENCY';

export const DATA_SETTING_ID_TYPE = 1702;
export const DATA_SETTING_ID_FORMULAR_OPERATOR = 1705;
export const DATA_SETTING_ID_FORMULAR_LOGICAL = 1710;
export const DATA_SETTING_ID_FORMULAR_TYPE = 1713;
export const DATA_SETTING_ID_FORMULAR_CURRENCY = 1715;

export const LOGICAL_ID_NONE = 1717;
export const COMMISSION_TYPE_ID_FIXED = 1703;
export const CURRENCY_ID_DEFAULT = 1716;
export const COMISSION_TYPE_ID_DEFAULT = 1714;
export const OPERATOR_ID_DEFAULT = 1706;
