entries = {
    student_survey: "./src/student_survey.js",
    tracking_visitor: "./src/tracking_visitor.js",
    tracking_notify_history: "./src/tracking_notify_history.js",
    documents: "./src/documents.js",
    report_agent_tpa: "./src/report_agent_tpa.js",
    list_tc: "./src/list_tc.js",
    bank_interest_rate: "./src/bank_interest_rate.js",
    mortgage: "./src/mortgage.js",
    pfs_list: "./src/pfs_list.js",
    ba_mortgage: "./src/ba_mortgage.js",
    pfs_detail: "./src/pfs_detail.js",
    pfs_overview_request: "./src/pfs_overview_request.js",
    kyc: "./src/kyc.js",
    change_card_type: "./src/change_card_type.js",
    log_score_card: "./src/log_score_card.js",
    deal_checking_planning: "./src/deal_checking_planning.js",
    classify_deal_hml: "./src/classify_deal_hml.js",
    commission_document: "./src/commission_document.js",
    commission_deal: "./src/commission_deal.js",
    commission_config: "./src/commission_config.js",
    commission_revenue_report: "./src/commission_revenue_report.js",
    crawler: "./src/crawler.js",
    property_matching_ranking_configuration:
        "./src/property_matching_ranking_configuration.js",
    tasks_of_bpo_listing: "./src/tasks_of_bpo_listing.js",
    tasks_of_comments: "./src/tasks_of_comments.js",
    demo: "./src/demo.js",
    lead: "./src/lead.js",
    bpo_zone_listing: "./src/bpo_zone_listing"
}
