export const SET_CRAWLER_DATA = 'SET_CRAWLER_DATA';
export const SET_DATA_POST = 'SET_DATA_POST';
export const SET_OPTION_LIST = 'SET_OPTION_LIST';
export const SET_SORTING = 'SET_SORTING';
export const CHANGE_SELECT = 'CHANGE_SELECT';
export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';
export const CHANGE_LOADING = 'CHANGE_LOADING';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const RESET_SELECT = 'RESET_SELECT';
export const RESET_FILTER_FORM = 'RESET_FILTER_FORM';
export const ON_ID_SELECTED_DATA = 'ON_ID_SELECTED_DATA';





