/*Bank Interest Rate*/
export const SHOW_HIDE_MODAL_BANK = 'SHOW_HIDE_MODAL_BANK';
export const SET_DATA_SEARCH = 'SET_DATA_SEARCH';
export const SET_DATA_POST = 'SET_DATA_POST';
export const SET_TABLE_BANK = 'SET_TABLE_BANK';
export const RESET_DATA_SEARCH = 'RESET_DATA_SEARCH';
export const RESET_DATA_POST = 'RESET_DATA_POST';
export const SAVE_BANK = 'SAVE_BANK';
export const SET_LIST_SELECT_BANK = 'SET_LIST_SELECT_BANK';
export const SET_FILTER_SELECT_BANK = 'SET_FILTER_SELECT_BANK';
/*Modal profile*/
export const SHOW_HIDE_MODAL_PROFILE = 'SHOW_HIDE_MODAL_PROFILE';
export const SET_DATA_POST_PROFILE = 'SET_DATA_POST_PROFILE';
export const RESET_DATA_POST_PROFILE = 'RESET_DATA_POST_PROFILE';
export const SET_DATA_LIST_PROFILE = 'SET_DATA_LIST_PROFILE';
export const SEND_PROFILE = 'SEND_PROFILE';