export const SHOW_HIDE_MODAL_CARD_TYPE = 'SHOW_HIDE_MODAL_CARD_TYPE';
export const SET_DATA_POST = 'SET_DATA_POST';
export const RESET_DATA_POST = 'RESET_DATA_POST';
export const SUBMIT = 'SUBMIT';
export const SET_LIST_SELECT_CARD_TYPE = 'SET_LIST_SELECT_CARD_TYPE';
export const SET_SELECT_CARD_TYPE = 'SET_SELECT_CARD_TYPE';
export const SET_DISABLE_SAVE = 'SET_DISABLE_SAVE';