export const GET_LIST_REASONS = "/deal/get-list-reason"
export const GET_LIST_CLONED_REASONS = "/deal/get-list-cloned-reasons"
export const UNLOCK_DEAL_LEAD = "/deal/unlock-deal-lead"
export const GET_DEAL_GROUP = "/kyc-api/get-deal-group"
export const SAVE_CLONED_DEAL = "/kyc-api/save-cloned-deal"
