export const SET_DOCUMENT_LIST = 'SET_DOCUMENT_LIST';
export const SET_TYPE_LIST = 'SET_TYPE_LIST';
export const SET_DETAIL_FORM = 'SET_DETAIL_FORM';
export const CHANGE_INPUT_FORM = 'CHANGE_INPUT_FORM';
export const CHANGE_CHECKBOX_FORM = 'CHANGE_CHECKBOX_FORM';
export const CHANGE_FILE_FORM = 'CHANGE_FILE_FORM';
export const CHANGE_DATE_FORM = 'CHANGE_DATE_FORM';
export const CHANGE_SELECT_FORM = 'CHANGE_SELECT_FORM';
export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';
export const DELETE_FILE_FORM = 'DELETE_FILE_FORM';
export const CHECK_ALL_VALIDATION = 'CHECK_ALL_VALIDATION';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLEAR_FORM = 'CLEAR_FORM';
export const REDIRECT = 'REDIRECT';

