version: '3.7'
services:

  # The Application
  app:
    image: ${AWSRepo}/dashboard_app:${TAG}
    container_name: dashboard-app
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./config/constants.php:/var/www/config/constants.php
      - ./storage:/var/www/storage
      - ./ckfinder/userfiles/images:/var/www/public/ckfinder/userfiles/images
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    tty: true
    ports:
      - "9000:9000"
# The Web Server
  web:
    image: ${AWSRepo}/dashboard_web:${TAG}
    container_name: dashboard-web
    working_dir: /var/www
    restart: unless-stopped
    tty: true
    ports:
      - "${PORT}:${PORT}"
      #- "443:443"
    volumes:
      - ./config/constants.php:/var/www/config/constants.php
      - ./storage:/var/www/storage
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./ckfinder/userfiles/images:/var/www/public/ckfinder/userfiles/images
    depends_on:
      - app