export const TOGGLE_LOADING = "TOGGLE_LOADING"
export const GET_LEAD_DETAIL = "GET_LEAD_DETAIL"
export const GET_LIST_MATCHING_LISTING = "GET_LIST_MATCHING_LISTING"
export const FORMAT_FILTER_FORM = "FORMAT_FILTER_FORM"
export const UPDATE_DATA_POST = "UPDATE_DATA_POST"

// get data modal
export const GET_ADJUST_CRITERIA = "GET_ADJUST_CRITERIA"
export const GET_CANCEL_REASONS = "GET_CANCEL_REASONS"
export const GET_REOPEN_REASONS = "GET_REOPEN_REASONS"
